### ISSUE TITLE
1: Host set up party for others to join

### ISSUE THREAD

**Issue by reddey4** [sopra-fs23-group-24/server#1]
I, as a host, want to host a game round that my friends can join. Upon starting to host, I can enter a username and get redirected to the lobby overview page.

- [x] sopra-fs23-group-24/client#2
- [x] sopra-fs23-group-24/client#1
- [x] sopra-fs23-group-24/server#41
- [x] sopra-fs23-group-24/server#42
- [x] #44

**Comment by lindasteiner2** [comment]
657e5f941c83a8bcad3c02863c7891112fa9ffc6

**Comment by lindasteiner2** [comment]
fb9b8b68d1cb0efe50117436e760c9de5aeebdeb

**Comment by lindasteiner2** [comment]
283e65dc3b30271f02731152e5079561e41f58f1
