### ISSUE TITLE
8: End of game see leaderboard

### ISSUE THREAD

**Issue by reddey4** [sopra-fs23-group-24/server#10]
As a player, at the end of the game, I want to see an overview over everyone’s scores with the winner highlighted. I have an option to leave the party. 

- [x] sopra-fs23-group-24/server#13
- [x] sopra-fs23-group-24/client#19
- [x] sopra-fs23-group-24/client#28
