### ISSUE TITLE
2: User join party and pick name, leave party again

### ISSUE THREAD

**Issue by reddey4** [sopra-fs23-group-24/server#2]
I as a user want to join a Lobby by typing the corresponding game code (that I get from the host) into the input field. I can enter a username and get redirected to the lobby overview page.

- [x] sopra-fs23-group-24/client#6
- [x] sopra-fs23-group-24/client#5
- [x] sopra-fs23-group-24/client#3
- [x] sopra-fs23-group-24/server#38
