### ISSUE TITLE
5.1: Fill out question prompts and click ready

### ISSUE THREAD

**Issue by reddey4** [sopra-fs23-group-24/server#6]
Players (users and hosts) have to fill out required question prompts. After filling out every question, players should click on ready.

- [x] sopra-fs23-group-24/server#20
- [x] sopra-fs23-group-24/server#21
- [x] sopra-fs23-group-24/client#17
- [x] sopra-fs23-group-24/client#16
- [x] sopra-fs23-group-24/client#15
- [x] sopra-fs23-group-24/client#14
- [x] sopra-fs23-group-24/client#13
- [x] sopra-fs23-group-24/server#27
- [x] sopra-fs23-group-24/client#24
- [x] #48 
- [x] #47 
- [x] #50
