### ISSUE TITLE
6: Answer a question in game

### ISSUE THREAD

**Issue by reddey4** [sopra-fs23-group-24/server#8]
As a player during the game, I want to be to shown a game-question and different answering options. I want to be able to select an answer by clicking on it. - In order to make a decision and submit my answer. Once everyone has submitted an answer or the timer has run out, I am redirected to a screen showing the correct answer and the current score. 

- [x] sopra-fs23-group-24/client#26
- [x] sopra-fs23-group-24/client#25
- [x] sopra-fs23-group-24/server#12
- [x] sopra-fs23-group-24/client#18
- [x] sopra-fs23-group-24/server#16
- [x] sopra-fs23-group-24/client#29
